channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.0
- pip:
  - mlflow==2.17.0
  - cloudpickle==3.1.0
  - feature-engine==1.8.1
  - numpy==2.1.2
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
